services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./google-credentials.json:/var/www/html/google-credentials.json
    networks:
      - laravel-network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel-network
    depends_on:
      - app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-worker
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./google-credentials.json:/var/www/html/google-credentials.json
    networks:
      - laravel-network
    depends_on:
      - mysql
    command: /usr/local/bin/worker-startup.sh
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local 